DORM default adapter in master branch might be changed to Firebird
The main idea is that users who don't have enterprise editions of IDE face compilation errors:

[dcc32 Fatal Error] dorm.adapter.FireDac.SQLServer.pas(8): F2613 Unit 'FireDAC.Phys.MSSQL' not found.

Which  is caused by the fact that MS SQL connection feature is not provided for pro and community version users.

https://www.embarcadero.com/ru/products/rad-studio/firedac